
- hosts: deploy,nginx_letsencrypt
  become: yes
  tasks:
    - name: certbot install
      shell: "[ -x /usr/bin/certbot ] || (dnf install epel-release -y &&  dnf install certbot python3-certbot-nginx -y)"

