
- hosts: deploy,nginx_letsencrypt
  become: yes
  tasks:
    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Install certbot and python3-certbot-nginx
      dnf:
        name:
          - certbot
          - python3-certbot-nginx
        state: present

