# 须带环境变量运行：
# ansible-playbook install-config-certbot-ENV.yml  -e "RUN_ENV=${RUN_ENV}"

# cron
# 一般域名证书
- hosts: nginx_letsencrypt
  user: root
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
  tasks:
    - name: crontab - letsencrypt
      cron: name=letsencrypt backup=yes state=present minute=11 hour=0 day=* month=* weekday=* user=root job="python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/bin/certbot renew > /dev/null && /usr/bin/systemctl reload nginx.service || /usr/local/bin/dingding_conver_to_markdown_list.py '【Error:证书更新:nginx】' '证书renew失败，请检查' > /dev/null "
      when: RUN_ENV != "dev"


# 泛域名证书
- hosts: deploy
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
    - ZZXIA_OP_SUPER_INVINCIBLE_LOLLIPOP_HOME: "{{ lookup('env','ZZXIA_OP_SUPER_INVINCIBLE_LOLLIPOP_HOME') }}"
  tasks:
    - name: crontab - letsencrypt-wildcart
      cron: name=letsencrypt-wildcart backup=yes state=present minute=0 hour=0 day=*  month=* weekday=* user=root job="python -c 'import random; import time; time.sleep(random.random() * 3600)' && {{ ZZXIA_OP_SUPER_INVINCIBLE_LOLLIPOP_HOME }}/tools/cert-letsencrypt-wildcart.sh -y aly -u > /dev/null"
      when: RUN_ENV == "stag"
    - name: crontab - letsencrypt-wildcart
      cron: name=letsencrypt-wildcart backup=yes state=present minute=0 hour=0 day=*  month=* weekday=* user=root job="python -c 'import random; import time; time.sleep(random.random() * 3600)' && {{ ZZXIA_OP_SUPER_INVINCIBLE_LOLLIPOP_HOME }}/tools/cert-letsencrypt-wildcart.sh -y godaddy -u > /dev/null"
      when: RUN_ENV == "prod"

