
# base profile
- hosts: all
  become: yes
  tasks:
    - name: 拷贝 - 系统profile相关
      copy: 
          src: '{{ item.srcc }}'
          dest: '{{ item.destt }}'
          owner: root
          group: root
          mode: 0644
          backup: no
      with_items:
        - { srcc: './zzxia-op-super-invincible-lollipop.run-env.sh', destt: '/etc/profile.d/' }
        - { srcc: './send_login_alert_msg.sh', destt: '/etc/profile.d/' }
    - name: 拷贝 - send_mail_attach_my_log.sh
      copy: src=./send_mail_attach_my_log.sh dest=/etc/cron.daily/ owner=root group=root mode=755  backup=no
    - name: 拷贝 - root用户profile相关
      copy: 
          src: '{{ item.srcc }}'
          dest: '{{ item.destt }}'
          owner: root
          group: root
          mode: 0644
          backup: yes
      with_items:
        - { srcc: './bashrc', destt: '/root/.bashrc' }
        - { srcc: './bash_logout', destt: '/root/.bash_logout' }
    - name: mailx - 拷贝mailrc、mailx_config.sh到/tmp
      copy: 
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
          owner: root
          group: root
          mode: 0755
          backup: no
      with_items: 
        - { src: './mailrc', dest: '/tmp/mailrc' }
        - { src: './mailx_config.sh', dest: '/tmp/mailx_config.sh' }
    - name: mailx - 追加到mail.rc
      shell: bash /tmp/mailx_config.sh >/dev/null 2>&1 && rm -f /tmp/mailrc /tmp/mailx_config.sh
    - name: 钉钉markdown - 拷贝到/usr/local/bin/
      copy: 
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
          owner: root
          group: root
          mode: 0755
          backup: no
      with_items: 
        - { src: '../../tools/dingding_send_markdown.sh', dest: '/usr/local/bin/' }
        - { src: '../../tools/dingding_conver_to_markdown_list.sh', dest: '/usr/local/bin/' }



