---
- name: Install and configure base software on Rocky Linux 9
  hosts: all
  become: yes
  tasks:
    - name: Install chrony for time synchronization
      dnf:
        name: chrony
        state: present
        disable_gpg_check: yes

    - name: Enable chronyd service
      service:
        name: chronyd
        enabled: yes

    - name: Restart chronyd service
      service:
        name: chronyd
        state: restarted

    - name: Update system and install base packages
      dnf:
        name:
          - bash-completion
          - iotop
          - bzip2
          - unzip
          - python3-pip
          - rsync
          - jq
          - yq
          - mailx
        state: present
        update_cache: yes  # 相当于 yum update -y

    - name: Install Python requests library via pip
      pip:
        name: requests
        state: present
        executable: pip3

    - name: Disable SELinux if currently enforcing
      block:
        - name: Check SELinux status
          command: getenforce
          register: selinux_status
          changed_when: false
          failed_when: false

        - name: Modify SELinux configuration to disabled
          lineinfile:
            path: /etc/selinux/config
            regexp: '^SELINUX='
            line: SELINUX=disabled
          when: selinux_status.stdout == "Enforcing"

        - name: Set SELinux to permissive mode immediately
          command: setenforce 0
          when: selinux_status.stdout == "Enforcing"

