
- hosts: deploy
  become: yes
  vars:
    - DEPLOY_HOME_BASE: "{{ lookup('env','DEPLOY_HOME_BASE') }}"
  tasks:
    - name: crontab - rm-image
      cron: name=deploy backup=yes state=present minute=0 hour=0 day=*  month=* weekday=*/1 user=root job='{{ DEPLOY_HOME_BASE }}/op/docker/rm-docker-image.sh -q -k gclife -d 7  >/dev/null'


- hosts: swarm,k8s
  become: yes
  tasks:
    - name: crontab - rm docker image and container
      cron: name=docker backup=yes state=present minute=0 hour=0 day=*  month=* weekday=* user=root job='docker image prune -a -f ; docker container prune -f'


