

- hosts: swarm_m
  become: yes
  tasks:
    - name: cp install-docker-remote-manage-agent.sh
      copy: src=./docker/install-docker-remote-manage-agent.sh  dest=/tmp/ mode=0755
    - name: install docker-remote-manage-agent
      shell: /tmp/install-docker-remote-manage-agent.sh


