

# repo-docker
- hosts: repo_docker
  become: yes
  tasks:
    - name: cp delete-docker-registry-image
      synchronize: src=./delete-docker-registry-image/  dest=/root/delete-docker-registry-image/  rsync_opts="--perms=yes,--times=yes"
    - name: crontab - delete-docker-registry-image
      cron: name=delete-docker-registry-image backup=yes state=present minute=0 hour=0 day=*  month=* weekday=* user=root job='export REGISTRY_DATA_DIR="/srv/docker/docker_registry/data/docker/registry/v2" ; cd /root/delete-docker-registry-image ; ./clean_old_versions.py -s ./delete_docker_registry_image.py  -i gclife-  -u https://127.0.0.1:5000 -l 20  -U ufipf -P 123456  --no_check_certificate > /dev/null ; docker exec -ti dockerregistry_docker-registry_1 registry garbage-collect /etc/docker/registry/config.yml > /dev/null'


