
- hosts: efk_e
  become: yes
  tasks:
    - name: cp elasticsearch-srv
      copy: src=./elasticsearch-srv/  dest=/srv/docker/elasticsearch-srv/  owner=root group=root mode=644 backup=yes
    - name: 设置执行权限
      shell: chmod  +x  /srv/docker/elasticsearch-srv/rm-es-history.sh
    - name: 设置数据目录权限
      shell: chown -R 1000:1000  /srv/docker/elasticsearch-srv/data01
    - name: 启动 elasticsearch-srv
      shell: cd /srv/docker/elasticsearch-srv/ && docker-compose up -d



