
# nginx-config
- hosts: nginx
  become: yes
  tasks:
    - name: 新建目录 nginx-config
      file: path=~/nginx-config  state=directory  mode=0755
    - name: 拷贝 nginx - nginx.list
      synchronize: src=./nginx-config/nginx.list      dest=~/nginx-config/nginx.list      rsync_opts="--perms=yes,--times=yes"
    - name: 拷贝 nginx - nginx-cert-letsencrypt-a.sh
      synchronize: src=./nginx-config/nginx-cert-letsencrypt-a.sh  dest=~/nginx-config/nginx-cert-letsencrypt-a.sh  rsync_opts="--perms=yes,--times=yes"
    - name: 拷贝 nginx - web-release.sh
      synchronize: src=./nginx-config/web-release-on-nginx.sh  dest=~/nginx-config/web-release-on-nginx.sh  rsync_opts="--perms=yes,--times=yes"


# cron
- hosts: nginx
  become: yes
  tasks:
    - name: crontab - htpass
      cron: name=htpass backup=yes state=present minute=0 hour=0 day=*  month=* weekday=* user=root job='echo "adm33`date +\%y\%-m\%-d`" | htpasswd -i -c /etc/nginx/conf.d/pass.db adm > /dev/null'
    - name: crontab - 清理build-log
      cron: name=清理build-log backup=yes state=present minute=0 hour=0 day=*  month=* weekday=* user=root job='find /srv/web_sites/build-log/releases/current/file/ -type d -ctime +3 | xargs rm -rf {} \; >/dev/null'


