
- hosts: repo_nexus
  become: yes
  tasks:
    - name: cp nexus
      copy: src=./nexus/  dest=/srv/docker/nexus/   owner=root group=root mode=644 backup=yes
    - name: 启动 nexus
      shell: chown 200:200 -R /srv/docker/nexus/nexus-data && cd /srv/docker/nexus && docker-compose up -d && echo "请根据readme完成仓库设置"



