# 须带环境变量运行：
# ansible-playbook  install-config-my_sec-ENV.yml  -e "RUN_ENV=${RUN_ENV}"
#
#
# 拷贝密码文件
#
# 请根据自己的需要修改此文件（主机与运行环境）
#
#
- hosts: deploy
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
  tasks:
    - name: 拷贝 - 用户密码工具
      copy:.
          src: '{{ item.srcc }}'
          dest: '{{ item.destt }}'
          owner: root
          group: root
          mode: 0700
          backup: yes
      with_items:
        - { srcc: './user-secret-update.sh', destt: '~/.my_sec/' }
        - { srcc: './user-token-update.sh', destt: '~/.my_sec/' }
        - { srcc: './user-manage.sh', destt: '~/.my_sec/' }
    - name: crontab - user-token-update
      cron: name=user-token-update backup=yes state=present minute=0 hour=0 day=*  month=* weekday=* user=root job='~/.my_sec/user-token-update.sh --update'
    - name: 拷贝 - user.db
      copy: src=./{{ RUN_ENV }}/user.db    dest=~/.my_sec/ owner=root group=root mode=0600  backup=no
    - name: 拷贝 - user.env.sec
      copy: src=./{{ RUN_ENV }}/user.env.sec    dest=~/.my_sec/ owner=root group=root mode=0600  backup=no
    - name: 拷贝 - dingding.sec
      copy: src=./{{ RUN_ENV }}/dingding.sec    dest=~/.my_sec/ owner=root group=root mode=0600  backup=no
    - name: 拷贝 - docker-repo.sec
      copy: src=./{{ RUN_ENV }}/docker-repo.sec dest=~/.my_sec/ owner=root group=root mode=0600  backup=no
    - name: 拷贝 - pg-server.sec
      copy: src=./{{ RUN_ENV }}/pg-server.sec dest=~/.my_sec/ owner=root group=root mode=0600  backup=no
    - name: 拷贝 - neo4j.sec
      copy: src=./{{ RUN_ENV }}/neo4j.sec dest=~/.my_sec/ owner=root group=root mode=0600  backup=no
    - name: 拷贝 - rabbitmq.sec
      copy: src=./{{ RUN_ENV }}/rabbitmq.sec dest=~/.my_sec/ owner=root group=root mode=0600  backup=no
    - name: 拷贝 - container-envs-pub.sec
      copy: src=./{{ RUN_ENV }}/container-envs-pub.sec dest=~/.my_sec/ owner=root group=root mode=0600  backup=no
    - name: 拷贝 - godaddy.sec
      copy: src=./{{ RUN_ENV }}/godaddy.sec dest=~/.my_sec/ owner=root group=root mode=0600  backup=no
      when: RUN_ENV == "prod"
    - name: 拷贝 - certbot-letencrypt-wildcardcertificates-sh.env
      copy: src=./{{ RUN_ENV }}/certbot-letencrypt-wildcardcertificates-sh.env  dest=~/.my_sec/certbot-letencrypt-wildcardcertificates-sh.env  owner=root group=root mode=0600  backup=no
      when: RUN_ENV == "stag" or RUN_ENV == "prod"
    - name: 拷贝 - aliyun-config.json
      copy: src=./{{ RUN_ENV }}/aliyun-config.json dest=~/.aliyun/config.json owner=root group=root mode=0600  backup=no
      when: RUN_ENV == "stag"


- hosts: swarm_m,efk,docker_compose
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
  tasks:
    - name: 拷贝 - docker-repo.sec
      copy: src=./{{ RUN_ENV }}/docker-repo.sec dest=~/.my_sec/ owner=root group=root mode=0600  backup=no

- hosts: all
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
  tasks:
    - name: 拷贝 - zzxia-ca.crt.pem
      copy: src=./{{ RUN_ENV }}/zzxia-ca.crt.pem   dest=/etc/pki/ca-trust/source/anchors/zzxia-ca.crt.pem  owner=root group=root mode=0600  backup=no
    - name: 更新os证书
      shell: update-ca-trust

- hosts: nginx
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
  tasks:
    - name: 拷贝 - 证书
      copy: src=./{{ RUN_ENV }}/mydomain.com/   dest=/srv/cert/mydomain.com/  owner=root group=root mode=0644  backup=no
      when: RUN_ENV == "dev"

- hosts: pg_m,gitlab
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
  tasks:
    - name: 拷贝 - passwd-ossfs
      copy: src=./{{ RUN_ENV }}/passwd-ossfs   dest=/etc/passwd-ossfs  owner=root group=root mode=0640  backup=no
      when: RUN_ENV == "stag" or RUN_ENV == "prod"


