
---
- name: Install and start Docker Registry service on Rocky Linux 9
  hosts: repo_docker
  become: yes
  tasks:
    - name: Ensure target directory exists
      file:
        path: /srv/docker_compose_services/docker_registry-srv
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy docker_registry-srv directory
      copy:
        src: ./docker_registry-srv/
        dest: /srv/docker_compose_services/docker_registry-srv/
        owner: root
        group: root
        mode: '0644'
        directory_mode: '0755'
        backup: yes

    - name: Start docker_registry-srv with Docker Compose
      docker_compose:
        project_src: /srv/docker_compose_services/docker_registry-srv
        state: present
        build: no
      register: compose_result

    - name: Display startup message
      debug:
        msg: "Docker Registry 已启动，请检查是否正常运行；根据 README 修改默认密码"
      when: compose_result.changed

