# 须带环境变量运行：
# ansible-playbook  install-config-my_private_envs.yml  -e "RUN_ENV=${RUN_ENV}"  -e "MY_PRIVATE_ENVS_DIR=${MY_PRIVATE_ENVS_DIR}"

- hosts: deploy
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
    - MY_PRIVATE_ENVS_DIR: "{{ lookup('env','MY_PRIVATE_ENVS_DIR') }}"
    - conf: "{{ lookup('file', '0-private-config-list.yml') | from_yaml }}"
  tasks:
    - name: 分发文件 (Deploy)
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0600') }}"
        backup: "{{ item.backup | default('no') }}"
      # 合并 common 和 当前环境 specific
      loop: "{{ (conf.deploy.common | default([])) + (conf.deploy.envs[RUN_ENV] | default([])) }}"

- hosts: all
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
    - conf: "{{ lookup('file', '0-private-config-list.yml') | from_yaml }}"
  tasks:
    - name: 分发文件 (All)
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0600') }}"
        backup: "{{ item.backup | default('no') }}"
      loop: "{{ (conf.all.common | default([])) + (conf.all.envs[RUN_ENV] | default([])) }}"
    
    # 特殊任务保留
    - name: 更新os证书
      shell: update-ca-trust

- hosts: nginx
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
    - conf: "{{ lookup('file', '0-private-config-list.yml') | from_yaml }}"
  tasks:
    - name: 分发文件 (Nginx)
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0600') }}"
        backup: "{{ item.backup | default('no') }}"
      loop: "{{ (conf.nginx.common | default([])) + (conf.nginx.envs[RUN_ENV] | default([])) }}"

- hosts: pg_m,gitlab
  become: yes
  vars:
    - RUN_ENV: "{{ lookup('env','RUN_ENV') }}"
    - conf: "{{ lookup('file', 'private-conf-vars.yml') | from_yaml }}"
  tasks:
    - name: 分发文件 (PG/Gitlab)
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0600') }}"
        backup: "{{ item.backup | default('no') }}"
      loop: "{{ (conf.pg_m_gitlab.common | default([])) + (conf.pg_m_gitlab.envs[RUN_ENV] | default([])) }}"
