# 须带环境变量运行：
# ansible-playbook install-config-pg-ENV.yml  -e "RUN_ENV=${RUN_ENV}"

- hosts: pg_m
  become: yes
  tasks:
    - name: 拷贝：backup
      copy: src=./pgbadger_report/  dest=/manage/pgbadger_report/  owner=root group=root mode=644 backup=yes
    - name: 加执行权限：pgbadger_generate_report.sh
      file: dest=/manage/pgbadger_report/pgbadger_generate_report.sh  state=file  owner=root group=root mode=0755
    - name: crontab - 生成pg报告
      cron: name=生成pg报告 backup=yes state=present minute=0 hour=1 day=*  month=* weekday=* user=root  job='/manage/pgbadger_report/pgbadger_generate_report.sh >> /manage/pgbadger_report/pgbadger_generate_report.sh.log'


