
- hosts: deploy
  become: yes
  vars:
    - ZZXIA_OP_SUPER_INVINCIBLE_LOLLIPOP_HOME: "{{ lookup('env','ZZXIA_OP_SUPER_INVINCIBLE_LOLLIPOP_HOME') }}"
  tasks:
    - name: crontab - rm-image
      cron: name=deploy backup=yes state=present minute=0 hour=0 day=*  month=* weekday=*/1 user=root job='{{ ZZXIA_OP_SUPER_INVINCIBLE_LOLLIPOP_HOME }}/tools/docker/rm-docker-image.sh -q -k gclife -d 7  >/dev/null'


- hosts: swarm,k8s,compose
  become: yes
  tasks:
    - name: crontab - rm docker image and container
      cron: name=docker backup=yes state=present minute=0 hour=0 day=*  month=* weekday=* user=root job='docker image prune -a -f > /dev/null ; docker container prune -f > /dev/null'


