
---
- name: Install and configure Nginx on Rocky Linux 9
  hosts: nginx
  become: yes
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: present
        disable_gpg_check: yes

    - name: Enable and start Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Install httpd-tools for htpasswd
      dnf:
        name: httpd-tools
        state: present
        disable_gpg_check: yes


