
#
- hosts: nginx
  become: yes
  tasks:
    - name: nginx install
      yum: name=nginx state=present disable_gpg_check=yes
    - name: nginx enable
      service: name=nginx enabled=true
    - name: nginx start
      service: name=nginx state=started
    - name: htpasswd install
      yum: name=httpd-tools state=present disable_gpg_check=yes



