version: "3"                                                                                                                                                                                   
services:
  mysql:
    # https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html
    image: mysql: 8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/db:/var/lib/mysql
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
      - ./conf/mysql/initdb.d:/docker-entrypoint-initdb.d    #如果有任何.sh或.sql你想它在创建后立即在数据库上运行脚本，把它放在这里
    env_file:
      - ./mysql.env
    environment:
      - MYSQL_LOG_CONSOLE=true
      #- MYSQL_ROOT_HOST=%        #默认情况下，MySQL创建 'root'@'localhost'帐户。只能从容器内部连接该帐户，例如MYSQL_ROOT_HOST=172.*.*.*
      #- MYSQL_ROOT_PASSWORD=1234567890
      #- MYSQL_ALLOW_EMPTY_PASSWORD=false
      #- MYSQL_ONETIME_PASSWORD=false
      #- MYSQL_RANDOM_ROOT_PASSWORD=false
      #
      #- MYSQL_DATABASE=nacos_config
      #- MYSQL_USER=unacos
      #- MYSQL_PASSWORD=nacos1234

    # https://dev.mysql.com/doc/refman/8.0/en/charset-server.html
    # 8.0 字符集与排序默认是utf8mb4与utf8mb4_0900_ai_ci，无需特别设置，这里只是为了记住
    # ai 指的是口音不敏感。也就是说，排序时 e，è，é，ê 和 ë 之间没有区别
    # ci 表示不区分大小写。也就是说，排序时 p 和 P 之间没有区别
    # --default-authentication-plugin=mysql_native_password  这是为了兼容5.x旧应用，8.0默认使用caching_sha2_password
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_0900_ai_ci'
      - '--default-authentication-plugin=mysql_native_password'


